### ISSUE TITLE
Failed to create AWS EC2 pad

### ISSUE THREAD

**Issue by paintenzero** [PierreBeucher/cloudypad#44] opened 2024-08-29 19:51 UTC
I finally got my quota increased on Amazon. I tried creating my first pad. It all went ok but the script hang on message:
```
Diagnostics:
  pulumi:pulumi:Stack (CloudyPad-AWS-awspad):
    Downloading provider: aws

Outputs:
    instanceId: "i-03<masked>6"
    publicIp  : "13.39.<masked>"

Resources:
    + 7 created

Duration: 37s
Executing playbook playbook.yml

- Wait for machine to be reachable (timeout: 10min) on hosts: all -
wait_for_connection...
  awspad failed | msg: timed out waiting for ping module test: Failed to connect to the host via ssh:
- Play recap -
  awspad                     : ok=0    changed=0    unreachable=0    failed=1    rescued=0    ignored=0
2024-08-29 19:53:55.094	ERROR	/dist/src/configurators/ansible.js:84	awspad	Ansible run failure: {"status":2,"signal":null,"output":[null,null,null],"pid":115,"stdout":null,"stderr":null}

/cloudypad/dist/src/configurators/ansible.js:85
            throw new Error(`Ansible run failed, exit code ${ansibleProcess.status}`);
                  ^
Error: Ansible run failed, exit code 2
    at AnsibleConfigurator.configure (/cloudypad/dist/src/configurators/ansible.js:85:19)
    at AwsInstanceInitializer.runConfiguration (/cloudypad/dist/src/core/initializer.js:67:28)
    at AwsInstanceInitializer.initializeInstance (/cloudypad/dist/src/core/initializer.js:109:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I can SSH into created VM using ubuntu user and public ip... So it is definitely up and reachable.

**Comment by PierreBeucher** [comment] 2024-08-30 09:52
Ansible is actually running in a Docker container, which may be why you can reach it from your host. Are you usign a VPN or some tool which manipulates IP tables (such as a security tool which are known to break Docker networking). Though Ansible should normally complain about timeout or ssh error...

Can you try to run a Docker container and connect via ssh ? Something like this:

```
docker run -v ~/.ssh:/root/.ssh:ro -it ubuntu bash
$ apt update && apt install ssh-client -y
$ ssh ubuntu@<HOST_IP>
```

To check if SSH connectivity works in a container.

Also, what OS are you on?

**Comment by paintenzero** [comment] 2024-08-30 20:39
I'm running the script from Debian 12 on OVH. I did what you said. It turned out that volumes /home/debian/{.ssh,.aws,.cloudypad,...} has been mounted as root. According to answer from https://serverfault.com/questions/984578/change-permissions-for-named-volumes-in-docker it is kinda expected behaviour.
```
Named volumes are initialized when first created to the contents of the image at the mount location. That initialization includes the owner and permissions. If /backup does not exist in your image, then an empty directory will be created and owned by root.
```
I tried to change Dockerfile created by cloudypad script and added creation of those folders. I removed generated image and recreated it. Still the same root owner...

Finally I added `--user 0` to docker cmd and rewrote mounts to /root folder. That worked for me and EC2 pad is finally created. I could pair Wolf with Moonlight. Now I get an empty games list. But that is another story for another issue.

I don't really know how to easily fix root ownership of volumes for unprivileged docker containers. I'm going to look further.

**Comment by PierreBeucher** [comment] 2024-08-31 07:24
The container should be running with a user with the same name and UID as host to avoid permission issue: in the container (eg. by running `docker exec -it <cloudypd_container> bash`) you should see the same owner as host for `.ssh` folders. Note **there are currently no named volume in Cloudy Pad**, only bind mounts, so the issue you encountered is likely not linked to a named volume permission issue. 

Here's what I see in a Cloudy Pad container on my end:

```myuser@5a55ceb90b37:/cloudypad$ ls -la ~ 
total 48
drwxr-xr-x 1 myuser users 4096 Aug 31 07:11 .
drwxr-xr-x 1 root     root  4096 Aug 31 07:01 ..
drwxr-xr-x 2 myuser users 4096 Feb 25  2024 .aws
drwxr-xr-x 5 myuser users 4096 Aug 30 13:52 .azure
-rw-r--r-- 1 myuser users  220 Mar 29 19:40 .bash_logout
-rw-r--r-- 1 myuser users 3526 Mar 29 19:40 .bashrc
drwx------ 5 myuser users 4096 Jul 24 10:21 .cloudypad
drwxr-xr-x 3 root     root  4096 Aug 31 07:11 .config
drwxr-xr-x 2 myuser users 4096 Jul 14 12:45 .paperspace
-rw-r--r-- 1 myuser users  807 Mar 29 19:40 .profile
drwxr-xr-x 2 myuser users 4096 Aug 31 06:39 .ssh
```

You can debug this by running hidden command `cloudypad debug-container`, it will drop you in a bash inside the same container used to run other commands. 

What may have happened is that your host `~/.ssh` didn't exists the first time you ran Cloudy Pad and got created on-the-fly by Docker with the bind mount (if a folder doesn't exist when using a bind mount Docker will create it as root). That would mean your home `~/.ssh` folder is currently owned by root, can you check that ? (`ls -al ~/.ssh` on your host)

This would actually be a bug as we don't want Cloudy Pad to create root-owned `~/.ssh` folder in user's home. Let me know please :)

Glad you could finally create your pad though ! Do not hesitate to create another issue for this: _Now I get an empty games list._ (you mean application list in Moonlight menu? Or when you connect via Steam you don't see your games?)

**Comment by ivryb** [comment] 2024-09-06 14:12
Seems like I have the same (or similar bug)

`cloudypad configure rybnikov`

here is the full output

[output.txt](https://github.com/user-attachments/files/16909211/output.txt)

**Comment by ivryb** [comment] 2024-09-06 14:22
[offtopic] I'm really amazed by what you're doing here, and I think I could participate.
I'm a pretty experienced full-stack/frontend developer, and I could create a nice web UI.
Here is the product that I'm currently developing (consider it like a portfolio or something :D): https://listenly.io

Maybe we could even create a cloud web version with hourly pay and a 50% markup or something, to make it easier accessible & cheaper than other cloud gaming services. Or something else.

**Comment by PierreBeucher** [comment] 2024-09-06 18:52
Looks like an error building the Nvidia driver Docker image, from your output:

```
100   433  100   433    0     0   1211      0 --:--:-- --:--:-- --:--:--  1212
#5 14.42 ./NVIDIA-Linux-x86_64-535.183.06.run: 2: Syntax error: newline unexpected
#5 ERROR: process "/bin/sh -c apt-get update -y &&     apt-get install -y --no-install-recommends curl ca-certificates kmod pkg-config libglvnd-dev vulkan-tools &&     curl -LO https://download.nvidia.com/XFree86/Linux-x86_64/$NV_VERSION/NVIDIA-Linux-x86_64-$NV_VERSION.run &&     chmod +x NVIDIA-Linux-x86_64-$NV_VERSION.run && mkdir -p /usr/nvidia &&     ./NVIDIA-Linux-x86_64-$NV_VERSION.run --silent -z --skip-depmod --skip-module-unload --no-nvidia-modprobe --no-kernel-modules --no-kernel-module-source --opengl-prefix=/usr/nvidia --wine-prefix=/usr/nvidia --utility-prefix=/usr/nvidia --utility-libdir=lib --compat32-prefix=/usr/nvidia --compat32-libdir=lib32 --egl-external-platform-config-path=/usr/nvidia/share/egl/egl_external_platform.d --glvnd-egl-config-path=/usr/nvidia/share/glvnd/egl_vendor.d --no-distro-scripts &&     rm ./NVIDIA-Linux-x86_64-$NV_VERSION.run" did not complete successfully: exit code: 2
------
 > [nvidia-installer 2/3] RUN apt-get update -y &&     apt-get install -y --no-install-recommends curl ca-certificates kmod pkg-config libglvnd-dev vulkan-tools &&     curl -LO https://download.nvidia.com/XFree86/Linux-x86_64/535.183.06/NVIDIA-Linux-x86_64-535.183.06.run &&     chmod +x NVIDIA-Linux-x86_64-535.183.06.run && mkdir -p /usr/nvidia &&     ./NVIDIA-Linux-x86_64-535.183.06.run --silent -z --skip-depmod --skip-module-unload --no-nvidia-modprobe --no-kernel-modules --no-kernel-module-source --opengl-prefix=/usr/nvidia --wine-prefix=/usr/nvidia --utility-prefix=/usr/nvidia --utility-libdir=lib --compat32-prefix=/usr/nvidia --compat32-libdir=lib32 --egl-external-platform-config-path=/usr/nvidia/share/egl/egl_external_platform.d --glvnd-egl-config-path=/usr/nvidia/share/glvnd/egl_vendor.d --no-distro-scripts &&     rm ./NVIDIA-Linux-x86_64-535.183.06.run:
13.55 Setting up libegl-dev:amd64 (1.4.0-1) ...
13.56 Setting up libgles-dev:amd64 (1.4.0-1) ...
13.57 Setting up libglvnd-dev:amd64 (1.4.0-1) ...
13.59 Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
13.61 Processing triggers for ca-certificates (20230311ubuntu0.22.04.1) ...
13.62 Updating certificates in /etc/ssl/certs...
14.01 0 added, 0 removed; done.
14.01 Running hooks in /etc/ca-certificates/update.d...
100   433  100   433    0     0   1211      0 --:--:-- --:--:-- --:--:--  1212
14.42 ./NVIDIA-Linux-x86_64-535.183.06.run: 2: Syntax error: newline unexpected
------
Dockerfile:4
--------------------
   3 |     ARG NV_VERSION
   4 | >>> RUN apt-get update -y && \
   5 | >>>     apt-get install -y --no-install-recommends curl ca-certificates kmod pkg-config libglvnd-dev vulkan-tools && \
   6 | >>>     curl -LO https://download.nvidia.com/XFree86/Linux-x86_64/$NV_VERSION/NVIDIA-Linux-x86_64-$NV_VERSION.run && \
   7 | >>>     chmod +x NVIDIA-Linux-x86_64-$NV_VERSION.run && mkdir -p /usr/nvidia && \
   8 | >>>     ./NVIDIA-Linux-x86_64-$NV_VERSION.run --silent -z --skip-depmod --skip-module-unload --no-nvidia-modprobe --no-kernel-modules --no-kernel-module-source --opengl-prefix=/usr/nvidia --wine-prefix=/usr/nvidia --utility-prefix=/usr/nvidia --utility-libdir=lib --compat32-prefix=/usr/nvidia --compat32-libdir=lib32 --egl-external-platform-config-path=/usr/nvidia/share/egl/egl_external_platform.d --glvnd-egl-config-path=/usr/nvidia/share/glvnd/egl_vendor.d --no-distro-scripts && \
   9 | >>>     rm ./NVIDIA-Linux-x86_64-$NV_VERSION.run
  10 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update -y &&     apt-get install -y --no-install-recommends curl ca-certificates kmod pkg-config libglvnd-dev vulkan-tools &&     curl -LO https://download.nvidia.com/XFree86/Linux-x86_64/$NV_VERSION/NVIDIA-Linux-x86_64-$NV_VERSION.run &&     chmod +x NVIDIA-Linux-x86_64-$NV_VERSION.run && mkdir -p /usr/nvidia &&     ./NVIDIA-Linux-x86_64-$NV_VERSION.run --silent -z --skip-depmod --skip-module-unload --no-nvidia-modprobe --no-kernel-modules --no-kernel-module-source --opengl-prefix=/usr/nvidia --wine-prefix=/usr/nvidia --utility-prefix=/usr/nvidia --utility-libdir=lib --compat32-prefix=/usr/nvidia --compat32-libdir=lib32 --egl-external-platform-config-path=/usr/nvidia/share/egl/egl_external_platform.d --glvnd-egl-config-path=/usr/nvidia/share/glvnd/egl_vendor.d --no-distro-scripts &&     rm ./NVIDIA-Linux-x86_64-$NV_VERSION.run" did not complete successfully: exit code: 2
```

This is new to me. Cloudypad uses a specific Dockerfile (see https://github.com/PierreBeucher/cloudypad/blob/790aaf1fab9ee27d9977adbcce66d52f719ec8d9/ansible/roles/wolf/files/docker-nvidia-volume.sh#L25) but maybe this Dockerfile is not reproducible and now broken. Have you tried again ? I'll try myself tomorrow and will update if necessary.

Thanks a lot for your feedbacks and encouragements :) I do have a platform + web UI in mind, though Cloudy Pad need to stabilize and gain a few features before coming to that. I'll make sure to let you know when this happens, in the meantime I'll happily discuss this by email (you can find it on my GitHub profile ;) )

**Comment by ivryb** [comment] 2024-09-06 19:03
Yep, I tried several times

Even tried on Google Cloud instead of AWS, exactly same error

**Comment by PierreBeucher** [comment] 2024-09-06 20:40
Damn, probably the Dockerfile broken then. It's an external dependency, will check this.

**Comment by PierreBeucher** [comment] 2024-09-06 21:13
Ok it seems to come from Nvidia driver `535.183.06`. Version `535.183.01` works. That may be a bug in the Dockerfile used to install driver. Will enquire.

**Comment by PierreBeucher** [comment] 2024-09-07 09:44
Fix incoming. This was an installation reproducibility error: driver installed was not always the same. I made sure we use a fixed driver version to avoid such issues in the future. Expect a new release by Sunday :)

**Comment by PierreBeucher** [comment] 2024-09-07 13:34
Fixed by https://github.com/PierreBeucher/cloudypad/pull/47 bot both bugs on this issue:

- Added notes about rootless Docker which caused @paintenzero bug
- Fixed driver installation reproducibility (also ensuring backward compatibility for existing boxes) @ivryb 

Release is in progress, will close this issue when ready.

**Comment by PierreBeucher** [comment] 2024-09-07 13:51
There you go: https://github.com/PierreBeucher/cloudypad/releases/tag/v0.6.0

**Closed by PierreBeucher** 2024-09-07 13:51 UTC

**Comment by ivryb** [comment] 2024-09-07 14:25
How can I update the version?
Do I also need to destroy created instances and create them again?

**Comment by PierreBeucher** [comment] 2024-09-07 15:30
You can run documented installation script again, it will try to install the latest version. 

As you never finished initial creation I'd recommend destroying half-deployed instance with `cloudypad destroy`. 

But you can try to finish configuration of provisioned instance with `cloudypad configure` + `cloudypad pair`

**Comment by ivryb** [comment] 2024-09-07 15:39
<img width="727" alt="image" src="https://github.com/user-attachments/assets/7cde6ec3-0664-4ce9-a70f-61431a5fdb7c">

it doesn't work -__-

**Comment by PierreBeucher** [comment] 2024-09-07 15:55
Erh. Odd. This output should appear after a prompt to override existing installation (see https://github.com/PierreBeucher/cloudypad/blob/master/install.sh#L22) 

Unless `read -p` didn't work... What OS are you running on? Can you download the install script and replace `set -e` by `set -ex` at the top before running again? It should print more debug info

**Comment by ivryb** [comment] 2024-09-07 15:57
The install script has this if condition which aborts the installation if it's cloudypad is already in PATH

![screenshot 2024-09-07 at 18 56 31@2x](https://github.com/user-attachments/assets/560d7fc5-6938-4c58-a2c5-82bb2a6feee5)

I downloaded the script, commented this `if`, and it worded

MacOS Sonoma

**Comment by ivryb** [comment] 2024-09-07 16:07
Yeah for some reason it doesnt asks for confirmation and just aborts it right away -___-

**Comment by PierreBeucher** [comment] 2024-09-07 16:10
Ok great, that was another possible workaround. Thanks for going through these bugs and providing feedback. 

Which shell are you running? Maybe is a portability issue if you are using fish or another shell Cloudy Pad may not support. I've seen issue with different version of `read` across OS and shells (there are tests for that but maybe I'm missing something)

**Comment by ivryb** [comment] 2024-09-07 16:12
I'm on zsh

**Comment by PierreBeucher** [comment] 2024-09-07 16:24
Will try to reproduce.

Have you got it working otherwise now?

**Comment by ivryb** [comment] 2024-09-07 16:30
Got a new error

seems like "Install linux-modules-extra package..." took too much time and the SSH connection was abruptly terminated

![screenshot 2024-09-07 at 19 27 27@2x](https://github.com/user-attachments/assets/dc96f85b-4ab2-4816-bf08-a42ba2242eaf)


I run `configure` again, and it finished

Pairing now, for the first time!

**Comment by ivryb** [comment] 2024-09-07 16:30
Oops, I doxxed my IP here xD

**Comment by ivryb** [comment] 2024-09-07 16:31
Got a new error

seems like "Install linux-modules-extra package..." took too much time and the SSH connection was abruptly terminated

![screenshot 2024-09-07 at 19 27 27@2x](https://github.com/user-attachments/assets/602bad6f-2c66-4d89-a9aa-c27703f6ba92)

I run configure again, and it finished

Pairing now, for the first time!

**Comment by PierreBeucher** [comment] 2024-09-07 17:32
Yay! I did have a freeze linux-extra once, I'll check why it goes stuck here. It's a simple apt install. 

Enjoy ;)

**Comment by PierreBeucher** [comment] 2024-09-08 19:26
@ivryb the "Installation aborted" issue should be solved with https://github.com/PierreBeucher/cloudypad/pull/51
