### ISSUE TITLE
AWS installation issue (ARM)

### ISSUE THREAD

**Issue by BranislavF** [PierreBeucher/cloudypad#62] opened 2024-10-14 15:38 UTC
Hello,

not sure if this is an issue as well using AWS, but when I try to create it, it gives me an error. It does not prompt me to enter the region  and it gives me such error. Maybe I am doing something wrong.

```
? Select Cloud provider: aws
? Enter instance name: Test
? Choose an SSH private key to connect to instance: /root/.ssh/id_ed25519
Using SSH private key /root/.ssh/id_ed25519
Creating instance Test
? Choose an instance type: g5.4xlarge
? Do you want to use spot instances ? Spot instances are cheaper (usually 20% to 70% off) but may be restarted any time. yes
? Enter desired disk size (GB): 100
? Use static Elastic IP or dynamic IP? : static
/cloudypad/node_modules/@smithy/config-resolver/dist-cjs/index.js:117
    throw new Error("Region is missing");
          ^

Error: Region is missing
    at default (/cloudypad/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
    at /cloudypad/node_modules/@smithy/node-config-provider/dist-cjs/index.js:90:104
    at /cloudypad/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at coalesceProvider (/cloudypad/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18)
    at /cloudypad/node_modules/@smithy/property-provider/dist-cjs/index.js:135:20
    at AwsInitializerPrompt.getCurrentRegion (/cloudypad/dist/src/providers/aws/initializer.js:118:16)
    at AwsInitializerPrompt.region (/cloudypad/dist/src/providers/aws/initializer.js:109:34)
    at AwsInitializerPrompt.prompt (/cloudypad/dist/src/providers/aws/initializer.js:46:24)
    at AwsInstanceInitializer.runProvisioning (/cloudypad/dist/src/providers/aws/initializer.js:19:22)

Node.js v20.16.0

```

**Comment by PierreBeucher** [comment] 2024-10-14 19:17
Hi there, thanks for using Cloudy Pad :)

AWS region must be set on your configuration, this is a generic error you'll probably get with AWS CLI commands as well. I recommend you setup your `~/.aws/config` with something like this:

```
[default]
region = eu-central-1 
```

Or another region which will be used as default - and by Cloudy Pad.

Alternatively you can set environment variable `AWS_REGION` 

See for details: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by BranislavF** [comment] 2024-10-23 19:30
Thank you for this update. Setuping AWS CLI is not so easy task, so maybe you can also add some straightforward steps for doing so? :) I know that there are some AWS docs, but they are huge and not so readable for casual user like me.

**Comment by PierreBeucher** [comment] 2024-10-24 06:20
Yeah a `--region` flag should be enough easy to add, though auto-detecting lack of region is harder to do. Will do the `--flag` soon and see for the other :)

**Comment by BranislavF** [comment] 2024-10-24 10:52
So, another issue, not sure if I am doing something wrong :)

```
? Select Cloud provider: aws
? Enter instance name: Testing
? Choose an SSH private key to connect to instance: /root/.ssh/id_ed25519
Using SSH private key /root/.ssh/id_ed25519
? Instance Testing already exists. Do you want to overwrite existing instance config? yes
Creating instance Testing
? Choose an instance type: g4dn.4xlarge
? Do you want to use spot instances ? Spot instances are cheaper (usually 20% to 70% off) but may be restarted any time. yes
? Enter desired disk size (GB): 100
? Use static Elastic IP or dynamic IP? : static
? Enter AWS region to use: eu-central-1
?
    You are about to provision AWS machine with the following details:
        Instance name: Testing
        Spot instance: true
        SSH key: /root/.ssh/id_ed25519
        AWS Region: eu-central-1
        Instance Type: g4dn.4xlarge
        Public IP Type: static
        Disk size: 100

    Do you want to proceed? yes
CommandError: code: -2
 stdout:
 stderr: Command failed with exit code 2: pulumi version
/usr/local/bin/pulumi/pulumi: 17: Syntax error: word unexpected (expecting ")")
 err?: Error: Command failed with exit code 2: pulumi version
/usr/local/bin/pulumi/pulumi: 17: Syntax error: word unexpected (expecting ")")

    at Object.createCommandError (/cloudypad/node_modules/@pulumi/automation/errors.ts:82:17)
    at /cloudypad/node_modules/@pulumi/automation/cmd.ts:217:15
    at Generator.throw (<anonymous>)
    at rejected (/cloudypad/node_modules/@pulumi/pulumi/automation/cmd.js:19:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by PierreBeucher** [comment] 2024-10-24 12:38
Well, that ones new. Which setup are you running Cloudy Pad in so I can try to reproduce? Which version are you using ? It seems you run as root, do you have any other specificities ? 

---

Coming back to your initial bug, I think solving Region issue is easy. `getCurrentRegion()` should simply not throw an error since it will ask for region anyway afterward. That was obvious now I come back to it, my bad. 

```
Error: Region is missing
    at default (/cloudypad/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
    at /cloudypad/node_modules/@smithy/node-config-provider/dist-cjs/index.js:90:104
    at /cloudypad/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at coalesceProvider (/cloudypad/node_modules/@smithy/property-provider/dist-cjs/index.js:124:18)
    at /cloudypad/node_modules/@smithy/property-provider/dist-cjs/index.js:135:20
    at AwsInitializerPrompt.getCurrentRegion (/cloudypad/dist/src/providers/aws/initializer.js:118:16)
    at AwsInitializerPrompt.region (/cloudypad/dist/src/providers/aws/initializer.js:109:34)
    at AwsInitializerPrompt.prompt (/cloudypad/dist/src/providers/aws/initializer.js:46:24)
    at AwsInstanceInitializer.runProvisioning (/cloudypad/dist/src/providers/aws/initializer.js:19:22)
```

**Comment by PierreBeucher** [comment] 2024-10-24 14:22
What's the output of `cloudypad --version` ?

**Comment by BranislavF** [comment] 2024-10-24 14:37
It is fresh installation:

0.7.0

**Comment by PierreBeucher** [comment] 2024-10-24 14:45
This one's very strange, it seems Pulumi (an underlying tool used to deploy infra) is failing to call `pulumi version` with this error: 

```
stderr: Command failed with exit code 2: pulumi version
/usr/local/bin/pulumi/pulumi: 17: Syntax error: word unexpected (expecting ")")
```

However Pulumi is installed within a container image and should have no issue. I can't reproduce easily, I'm gonna try to install the same way you did. Can you please specify:
- The Clouder you used
- Which version of Linux you installed on VPS
- Instance type you used (and if it's an ARM or X86/64 machine)

**Comment by BranislavF** [comment] 2024-10-24 15:07
Sure not a problem.

Cloud provider: Scaleway
Linux used: Ubuntu 24.04
Linux scw-kind-chaplygin 6.8.0-44-generic #44-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 13 14:20:20 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

It sounds it is an ARM instance, maybe that can cause issues ? I will try with x86 :) Completely missed that.

**Comment by PierreBeucher** [comment] 2024-10-24 15:59
> It sounds it is an ARM instance, maybe that can cause issues ? I will try with x86 :) Completely missed that.

Exactly what I had in mind, hence me asking for precision about architecture. That's probably a Pulumi install issue then, thanks for the details !

**Comment by BranislavF** [comment] 2024-10-28 09:57
Closing this as solved, reopen if you would like to track the ARM issue :)

**Comment by saxlamen** [comment] 2024-12-22 16:44
Tried install cloudypad on a Raspberry Pi 5 and encountered the same Pulumi issue. Is there a fix on ARM-based system?

**Comment by PierreBeucher** [comment] 2024-12-22 18:47
Haven't looked it up yet, will do soon! Let's reopen this for now. Can you use a AMD64 machine in the meantime?

**Comment by saxlamen** [comment] 2024-12-23 15:33
Thanks! Looking forward to  a solution, Will try on another system too.

**Comment by PierreBeucher** [comment] 2024-12-27 14:29
Found the problem. Docker image is ARM-based alright but install is hardcoded to download X64 version of Pulumi. Duh. 

https://github.com/PierreBeucher/cloudypad/blob/a10fbd11be302022d759da09149bd273cde28bfe/Dockerfile#L14

```sh
RUN curl "https://get.pulumi.com/releases/sdk/pulumi-${PULUMI_VERSION}-linux-x64.tar.gz" -o pulumi.tar.gz 
```

Will be fixed in next release.

**Comment by PierreBeucher** [comment] 2024-12-27 17:46
Should be fixed in https://github.com/PierreBeucher/cloudypad/releases/tag/v0.9.0

**Closed by PierreBeucher** 2024-12-27 17:46 UTC
